### ISSUE TITLE
Stuck in SplashScreen

### ISSUE THREAD

**Issue by barisakr** [firgia/soca#54]
Hello,

When I was trying to learn about Bloc, I came across your repository. Firstly, it looks fantastic, both in terms of architecture and conceptually, I must say. I have a question: when I cloned the repository for a trial, the project gets stuck at the SplashScreen. What do I need to do to overcome this?

I saw in the previous issue that it might be related to .env files. Do you have the opportunity to share a template of the .env file with dummy records? I added empty .env files buts still doesnt work

**Comment by firgia** [comment]
Hello, I'm sorry for the late answer and confused Documentation. 

You should create 3 env it's called **.env.development** , **.env.staging** and **.env.production**.
This is the sample .env file. Hopefully, it can help you to, please let me know if you have any issue

```
AGORA_APP_ID = ******
AGORA_APP_CERTIFICATE = ******
ONESIGNAL_URL_PLAYERS = https://onesignal.com/api/v1/players
ONESIGNAL_URL_NOTIFICATIONS = https://onesignal.com/api/v1/notifications
ONESIGNAL_APP_ID = ******
ONESIGNAL_VOIP_APP_ID = ******
ONESIGNAL_REST_API_KEY = ******
ONESIGNAL_VOIP_REST_API_KEY = ******
ONESIGNAL_ANDROID_CHANNEL_ID_SYSTEM_IMPORTANT = ******
ONESIGNAL_ANDROID_CHANNEL_ID_SYSTEM_ACCOUNT = ******
```

**Comment by barisakr** [comment]
Thank you!

I appreciated for your answer. I downgraded the version of the "go_router" package from "13.0.0" to "7.0.0" and it helped. 
With new version of "go_router", I couldn't trigger the Observer class.

Wish you best!
Regards.
